### ISSUE TITLE
Rotate caret in side panel when drop down opened

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/wetland-projects-v2#12]

**Comment by kjacobsen16** [comment]
problem related to wim-styles not applying change

**Comment by HansVraga** [comment]
@lprivette you figured out the fix to this, right?

**Comment by lprivette** [comment]
Yes. This commit in Decadal: v2 https://github.com/USGS-WiM/nawqa-decadal-v2/commit/0097099f95ad1c7c72b88adbd6a339d1f77367db shows what I did.

I think Mitch said he'll have a fix for it in the new styles
