### ISSUE TITLE
s3 bucket access to usgswim for katrin

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/wetland-projects-v2#14]
Katrin needs an access key/secret key for accessing our s3 buckets

**Comment by aaronstephenson** [comment]
Please clarify which AWS account and which buckets. By creating a ticket here, you are implying just "wetlands" buckets, which don't exist.

**Comment by troddick** [comment]
Is there a place to create a ticket for not-project-specific requests? I only put it here because she is working on this project and needs access to the s3 bucket test.wim.usgs.gov to add/update the app.
I didn't realize there are several AWS s3 accounts or a separation of the buckets (from an access key perspective). She may need access to other buckets, but at this time, it's just the test.wim.usgs.gov for this app until it goes live. 
Thanks. Let me know if I'm not answering your questions correctly.

**Comment by aaronstephenson** [comment]
Non-project-specific requests should go here:
https://github.com/USGS-WiM/wim-infrastructure/issues/

We currently have 7 AWS accounts, soon to be several more, and each one has distinct and independent user accounts and services.

I'll get Katrin set up with access to the test.wim.usgs.gov S3 bucket.

**Comment by troddick** [comment]
OK. Thanks Aaron.

**Comment by aaronstephenson** [comment]
Done. Email sent to Katrin.
