### ISSUE TITLE
Update 'Find Location' 

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/wetland-projects-v2#8]
Use 'Find Location' in SWI mapper as example

**Comment by lprivette** [comment]
I think the SWI mapper is using the ESRI search no? 

@HansVraga do we want to use the usgs/texas search for this one or just stick with the ESRI one for consistency between apps?

**Comment by HansVraga** [comment]
Stick with ESRI search for now.

**Comment by kjacobsen16** [comment]
done
